version: "3"

volumes:
  pg_data:

services:
  postgres-website:
    image: postgres:10.0
    container_name: postgres-website
    restart: always
    ports:
      - "5432:5432"
    # Data persistence, comment out the following two lines to disable
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=origin
      - POSTGRES_PASSWORD=origin
      - POSTGRES_DB=origin_website

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=4096

  origin-website:
    container_name: origin-website
    build:
      context: .
      dockerfile: ./Dockerfile
    image: origin-website
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
    depends_on:
      - postgres-website
      - redis
    ports:
      - "5000:5000"
      - "5555:5555"
    environment:
      - FLASK_APP=/app/main.py
    command:
      >
      /bin/bash -c "flask db upgrade &&
      python /app/main.py"

  celery:
    container_name: celery
    image: origin-website
    user: nobody
    depends_on:
      - postgres-website
      - redis
    volumes:
      - ./:/app
      - ./docker.env:/app/.env
    environment:
      - FLASK_APP=/app/main.py
    command:
      >
      /bin/bash -c "/usr/local/bin/watchmedo auto-restart -d . -p '*.py' -i '*.pyc' --recursive --
      celery -A util.tasks worker --loglevel=INFO"
